# Generated by Django 4.0.5 on 2022-06-04 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Refinitiv',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('ESG_score', models.IntegerField(default=0)),
                ('rank', models.CharField(max_length=200)),
                ('environment', models.IntegerField(default=0)),
                ('social', models.IntegerField(default=0)),
                ('governance', models.IntegerField(default=0)),
                ('company_ticker', models.CharField(max_length=200)),
            ],
        ),
    ]
